[alpha]
number = 1
alternatives = ['a']

[beta]
number = 1
alternatives = ['b']

[delta]
number = 1
alternatives = ['d']

[file]
minimum = 1
maximum = 9
alternatives = ['f']

[help]
number = 0
alternatives = ['h', 'x']

[initial]
minimum = 1
maximum = 2
alternatives = ['i']

[kernel]
minimum = 1
maximum = 9
alternatives = ['k']

[list-methodologies]
number = 0

[methodology]
number = 1

[report]
number = 0
alternatives = ['r']

[variance]
number = 1
alternatives = ['v']

[version]
number = 0
alternatives = ['V']

